#!/usr/bin/env ruby

$:.unshift File.expand_path(File.join(File.expand_path(__FILE__), "..", "..", "lib"))

require File.expand_path(File.join(File.expand_path(__FILE__), "..", "..", "lib", "escort_ng"))

module Basic
  class Application < Escort::Application
    command_map do |m|
      m.default_command do
        p 'HELLO'
      end
    end
  end
end

Basic::Application.run
